[package]
name = "zellij-choose-tree"
version = "0.4.0"
edition = "2021"
description = "Zellij plugin to quickly switch between sessions, inspired by tmux choose-tree"
license = "MIT"

[dependencies]
zellij-tile = "0.41.1"
